version: "3"
services:
  api-server:
    container_name: viettrade-api
    build: ./
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - viettrade-network
    depends_on:
      - db
    volumes:
      - ./:/app
  db:
    image: mysql:8.0
    container_name: viettrade-db
    restart: always
    ports:
      - "33061:3306"
    networks:
      - viettrade-network
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: viettrade
      MYSQL_USER: viettrade
      MYSQL_PASSWORD: viettrade
    command:
      [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password' ]
    volumes:
      - ./databases:/var/lib/mysql
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: viettrade-phpmyadmin
    restart: unless-stopped
    ports:
      - '8090:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: secret
      UPLOAD_LIMIT: 300M
    networks:
      - viettrade-network
networks:
  viettrade-network:
    driver: bridge