import { NextFunction, Request, Response } from 'express';
import { FORBIDDEN } from 'http-status';

import { types } from '../../common';

const Role = types.user.Role;
const FullAccess = [Role.ADMIN, Role.USER, Role.CONTENT];

const NotUserAccess = [Role.ADMIN, Role.CONTENT];

export const apiList = {
  userSearch: 'userSearch',
  userDelete: 'userDelete',
  userSearchId: 'userSearchId',
  userCreate: 'userCreate',
  userUpdate: 'userUpdate',
  userUpdateSelf: 'userUpdateSelf',
  adminSearch: 'adminSearch',
  adminDelete: 'adminDelete',
  adminSearchId: 'adminSearchId',
  adminInfo: 'adminInfo',
  adminCreate: 'adminCreate',
  adminUpdate: 'adminUpdate',
  categoryCreate: 'categoryCreate',
  categoryUpdate: 'categoryUpdate',
  categorySearchId: 'categorySearchId',
  categorySearch: 'categorySearch',
  categoryDelete: 'categoryDelete',
  categoryDocumentCreate: 'categoryDocumentCreate',
  categoryDocumentUpdate: 'categoryDocumentUpdate',
  categoryDocumentSearchId: 'categoryDocumentSearchId',
  categoryDocumentSearch: 'categoryDocumentSearch',
  categoryDocumentDelete: 'categoryDocumentDelete',
  postCreate: 'postCreate',
  postUpdate: 'postUpdate',
  postDelete: 'postDelete',
  postSearchId: 'postSearchId',
  postSearch: 'postSearch',
  projectCreate: 'projectDelete',
  projectUpdate: 'projectUpdate',
  projectDelete: 'projectDelete',
  projectSearchId: 'projectSearchId',
  projectSearch: 'projectSearch',
  documentCreate: 'documentCreate',
  documentUpdate: 'documentUpdate',
  documentDelete: 'documentDelete',
  documentSearchId: 'documentSearchId',
  documentSearch: 'documentSearch',
  companyCreate: 'companyCreate',
  companyUpdate: 'companyUpdate',
  companyUpdateDisplay: 'companyUpdateDisplay',
  companyDelete: 'companyDelete',
  companySearch: 'companySearch',
  companySearchId: 'companySearchId',
  slideCreate: 'slideCreate',
  slideUpdate: 'slideUpdate',
  slideDelete: 'slideDelete',
  slideSearch: 'slideSearch',
  slideUpdateDisplay: 'slideUpdateDisplay',
  galleryCreate: 'galleryCreate',
  galleryUpdate: 'galleryUpdate',
  galleryDelete: 'galleryDelete',
  gallerySearch: 'gallerySearch',
  publicationCreate: 'publicationCreate',
  publicationUpdate: 'publicationUpdate',
  publicationDelete: 'publicationDelete',
  publicationSearch: 'publicationSearch',
  questionCreate: 'questionCreate',
  questionUpdate: 'questionUpdate',
  questionDelete: 'questionDelete',
  questionSearch: 'questionSearch',
  structureCreate: 'structureCreate',
  structureUpdate: 'structureUpdate',
  structureDelete: 'structureDelete',
  structureSearch: 'structureSearch',
  structureUpdateDisplay: 'structureUpdateDisplay',
  departmentCreate: 'departmentCreate',
  departmentUpdate: 'departmentUpdate',
  departmentDelete: 'departmentDelete',
  departmentSearch: 'departmentSearch',
  menuCreate: 'menuCreate',
  menuUpdate: 'menuUpdate',
  menuDelete: 'menuDelete',
  menuSearch: 'menuSearch',
  menuUpdateDisplay: 'menuUpdateDisplay',
  digitalCreate: 'digitalCreate',
  digitalUpdate: 'digitalUpdate',
  digitalDelete: 'digitalDelete',
  digitalSearch: 'digitalSearch',
  digitalUpdateDisplay: 'digitalUpdateDisplay'
};

export const permissions = {
  [apiList.userSearch]: FullAccess,
  [apiList.userSearchId]: FullAccess,
  [apiList.userDelete]: NotUserAccess,
  [apiList.userCreate]: FullAccess,
  [apiList.userUpdate]: FullAccess,
  [apiList.userUpdateSelf]: FullAccess,
  [apiList.adminSearch]: FullAccess,
  [apiList.adminSearchId]: FullAccess,
  [apiList.adminInfo]: FullAccess,
  [apiList.adminDelete]: NotUserAccess,
  [apiList.adminCreate]: NotUserAccess,
  [apiList.adminUpdate]: FullAccess,
  [apiList.categoryCreate]: FullAccess,
  [apiList.categoryUpdate]: FullAccess,
  [apiList.categoryDelete]: FullAccess,
  [apiList.categorySearchId]: FullAccess,
  [apiList.categorySearch]: FullAccess,
  [apiList.categoryDocumentCreate]: FullAccess,
  [apiList.categoryDocumentUpdate]: FullAccess,
  [apiList.categoryDocumentDelete]: FullAccess,
  [apiList.categoryDocumentSearchId]: FullAccess,
  [apiList.categoryDocumentSearch]: FullAccess,
  [apiList.postCreate]: FullAccess,
  [apiList.postUpdate]: FullAccess,
  [apiList.postDelete]: FullAccess,
  [apiList.postSearchId]: FullAccess,
  [apiList.postSearch]: FullAccess,

  [apiList.projectCreate]: FullAccess,
  [apiList.projectUpdate]: FullAccess,
  [apiList.projectDelete]: FullAccess,
  [apiList.projectSearchId]: FullAccess,
  [apiList.projectSearch]: FullAccess,

  [apiList.documentCreate]: FullAccess,
  [apiList.documentUpdate]: FullAccess,
  [apiList.documentDelete]: FullAccess,
  [apiList.documentSearchId]: FullAccess,
  [apiList.documentSearch]: FullAccess,
  [apiList.companyCreate]: FullAccess,
  [apiList.companyUpdate]: FullAccess,
  [apiList.companyUpdateDisplay]: FullAccess,
  [apiList.companyDelete]: FullAccess,
  [apiList.companySearchId]: FullAccess,
  [apiList.companySearch]: FullAccess,
  [apiList.slideCreate]: NotUserAccess,
  [apiList.slideUpdate]: NotUserAccess,
  [apiList.slideDelete]: NotUserAccess,
  [apiList.slideSearch]: FullAccess,
  [apiList.slideUpdateDisplay]: NotUserAccess,
  [apiList.galleryCreate]: NotUserAccess,
  [apiList.galleryUpdate]: NotUserAccess,
  [apiList.galleryDelete]: NotUserAccess,
  [apiList.gallerySearch]: FullAccess,
  [apiList.publicationCreate]: NotUserAccess,
  [apiList.publicationUpdate]: NotUserAccess,
  [apiList.publicationDelete]: NotUserAccess,
  [apiList.publicationSearch]: FullAccess,
  [apiList.questionCreate]: NotUserAccess,
  [apiList.questionUpdate]: NotUserAccess,
  [apiList.questionDelete]: NotUserAccess,
  [apiList.questionSearch]: FullAccess,
  [apiList.structureCreate]: NotUserAccess,
  [apiList.structureUpdate]: NotUserAccess,
  [apiList.structureDelete]: NotUserAccess,
  [apiList.structureSearch]: FullAccess,
  [apiList.structureUpdateDisplay]: NotUserAccess,
  [apiList.departmentCreate]: NotUserAccess,
  [apiList.departmentUpdate]: NotUserAccess,
  [apiList.departmentDelete]: NotUserAccess,
  [apiList.departmentSearch]: FullAccess,
  [apiList.menuCreate]: NotUserAccess,
  [apiList.menuUpdate]: NotUserAccess,
  [apiList.menuDelete]: NotUserAccess,
  [apiList.menuSearch]: NotUserAccess,
  [apiList.menuUpdateDisplay]: NotUserAccess,
  [apiList.digitalCreate]: NotUserAccess,
  [apiList.digitalUpdate]: NotUserAccess,
  [apiList.digitalDelete]: NotUserAccess,
  [apiList.digitalSearch]: FullAccess,
  [apiList.digitalUpdateDisplay]: NotUserAccess,
  [apiList.projectCreate]: FullAccess,
  [apiList.projectUpdate]: FullAccess,
  [apiList.projectDelete]: FullAccess,
  [apiList.projectSearchId]: FullAccess,
  [apiList.projectSearch]: FullAccess
};

/**
 * prevent user enter api without authorization
 * @param apiName name of api, define in `apiList`
 */
export const routeGuard = (apiName: string) => {
  const apiPermission = permissions[apiName];
  return (req: Request, res: Response, next: NextFunction) => {
    if (req.user && apiPermission.indexOf(req.user!.role!) >= 0) {
      next();
    } else {
      res.status(FORBIDDEN).json({
        errors: ['Unauthorized URL']
      });
    }
  };
};
