export const API_ROOT = process.env.NEXT_PUBLIC_HOST;
export const TIMEOUT = 10000;

// eslint-disable-next-line import/no-anonymous-default-export
export default {
  API_ROOT,
  TIMEOUT,
  NEWS: {
    DETAIL: "/posts",
  },
  CATEGORY: {
    LIST: "/category",
    CREATE: "/category",
    DETAIL: "/category/:id",
    UPDATE: "/category/:id",
    UPDATE_DISPLAY: "/category/display/:id",
    DELETE: "/category/:id",
  },
  POST: {
    LIST: "/post",
    CREATE: "/post",
    UPDATE: "/post/:id",
    DETAIL: "/post/:id",
    DELETE: "/post/:id",
    APPROVE: "/post/approve/:id",
  },
  PROJECT: {
    LIST: "/project",
    CREATE: "/project",
    UPDATE: "/project/:id",
    DETAIL: "/project/:id",
    DELETE: "/project/:id",
  },
  AUTH: {
    LOGIN: "/auth/login/admin",
  },
  USER: {
    LIST: "/user",
    CREATE: "/user",
    DETAIL: "user/:id",
    UPDATE: "/user/:id",
    DELETE: "/user/:id",
  },
  BANNER: {
    LIST: "/slide",
    CREATE: "/slide",
    UPDATE: "/slide/:id",
    UPDATE_DISPLAY: "/slide/display",
    DETAIL: "/slide/:id",
    DELETE: "/slide/:id",
  },
  ADMIN: {
    LIST: "/admin",
    CREATE: "/admin",
    DETAIL: "/admin/:id",
    INFO: "/admin/adminInfo",
    UPDATE: "/admin/:id",
    DELETE: "/admin/:id",
  },
  COMPANY: {
    LIST: "/company",
    LIST_ALL: "/company/all",
    CREATE: "/company",
    DETAIL: "/company/:id",
    UPDATE: "/company/:id",
    UPDATE_DISPLAY: "/company/display/:id",
    DELETE: "/company/:id",
    APPROVE: "/company/approve/:id",
  },
  MEDIA: {
    LIST: "/gallery",
    CREATE: "/gallery",
    UPDATE: "/gallery/:id",
    DETAIL: "/gallery/:id",
    DELETE: "/gallery/:id",
  },
  PUBLICATION: {
    LIST: "/publication",
    CREATE: "/publication",
    DETAIL: "/publication/:id",
    UPDATE: "/publication/:id",
    DELETE: "/publication/:id",
  },
  QUESTION: {
    LIST: "/question",
    CREATE: "/question",
    DETAIL: "/question/:id",
    UPDATE: "/question/:id",
    DELETE: "/question/:id",
  },
  STRUCTURE: {
    LIST_ALL: "/structure/all",
    LIST: "/structure",
    CREATE: "/structure",
    DETAIL: "/structure/:id",
    UPDATE: "/structure/:id",
    DELETE: "/structure/:id",
    LIST_SUB_STRUCTURE: "/structure/substructure/:id",
    UPDATE_DISPLAY: "/structure/display",
  },
  CATEGORY_DOCUMENT: {
    LIST: "/category-document",
    CREATE: "/category-document",
    DETAIL: "/category-document/:id",
    UPDATE: "/category-document/:id",
    DELETE: "/category-document/:id",
  },
  DOCUMENT: {
    LIST: "/document",
    CREATE: "/document",
    DETAIL: "/document/:id",
    UPDATE: "/document/:id",
    DELETE: "/document/:id",
  },
  MENU: {
    LIST: "/menu",
    CREATE: "/menu",
    DETAIL: "/menu/:id",
    UPDATE: "/menu/:id",
    DELETE: "/menu/:id",
    UPDATE_DISPLAY: "/menu/display",
    LIST_SUB_MENU: "/menu/submenu/:id",
  },
  DEPARTMENT: {
    LIST: "/department/all",
    CREATE: "/department",
    DETAIL: "/department/:id",
    UPDATE: "/department/:id",
    DELETE: "/department/:id",
  },
  DIGITAL: {
    LIST: "/digital",
    CREATE: "/digital",
    DETAIL: "/digital/:id",
    UPDATE: "/digital/:id",
    DELETE: "/digital/:id",
    UPDATE_DISPLAY: "/digital/display",
  },
};
