"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.routeGuard = exports.permissions = exports.apiList = void 0;
const http_status_1 = require("http-status");
const common_1 = require("../../common");
const Role = common_1.types.user.Role;
const FullAccess = [Role.ADMIN, Role.USER, Role.CONTENT];
const NotUserAccess = [Role.ADMIN, Role.CONTENT];
exports.apiList = {
    userSearch: 'userSearch',
    userDelete: 'userDelete',
    userSearchId: 'userSearchId',
    userCreate: 'userCreate',
    userUpdate: 'userUpdate',
    userUpdateSelf: 'userUpdateSelf',
    adminSearch: 'adminSearch',
    adminDelete: 'adminDelete',
    adminSearchId: 'adminSearchId',
    adminInfo: 'adminInfo',
    adminCreate: 'adminCreate',
    adminUpdate: 'adminUpdate',
    categoryCreate: 'categoryCreate',
    categoryUpdate: 'categoryUpdate',
    categorySearchId: 'categorySearchId',
    categorySearch: 'categorySearch',
    categoryDelete: 'categoryDelete',
    categoryDocumentCreate: 'categoryDocumentCreate',
    categoryDocumentUpdate: 'categoryDocumentUpdate',
    categoryDocumentSearchId: 'categoryDocumentSearchId',
    categoryDocumentSearch: 'categoryDocumentSearch',
    categoryDocumentDelete: 'categoryDocumentDelete',
    postCreate: 'postCreate',
    postUpdate: 'postUpdate',
    postDelete: 'postDelete',
    postSearchId: 'postSearchId',
    postSearch: 'postSearch',
    projectCreate: 'projectDelete',
    projectUpdate: 'projectUpdate',
    projectDelete: 'projectDelete',
    projectSearchId: 'projectSearchId',
    projectSearch: 'projectSearch',
    documentCreate: 'documentCreate',
    documentUpdate: 'documentUpdate',
    documentDelete: 'documentDelete',
    documentSearchId: 'documentSearchId',
    documentSearch: 'documentSearch',
    companyCreate: 'companyCreate',
    companyUpdate: 'companyUpdate',
    companyUpdateDisplay: 'companyUpdateDisplay',
    companyDelete: 'companyDelete',
    companySearch: 'companySearch',
    companySearchId: 'companySearchId',
    slideCreate: 'slideCreate',
    slideUpdate: 'slideUpdate',
    slideDelete: 'slideDelete',
    slideSearch: 'slideSearch',
    slideUpdateDisplay: 'slideUpdateDisplay',
    galleryCreate: 'galleryCreate',
    galleryUpdate: 'galleryUpdate',
    galleryDelete: 'galleryDelete',
    gallerySearch: 'gallerySearch',
    publicationCreate: 'publicationCreate',
    publicationUpdate: 'publicationUpdate',
    publicationDelete: 'publicationDelete',
    publicationSearch: 'publicationSearch',
    questionCreate: 'questionCreate',
    questionUpdate: 'questionUpdate',
    questionDelete: 'questionDelete',
    questionSearch: 'questionSearch',
    structureCreate: 'structureCreate',
    structureUpdate: 'structureUpdate',
    structureDelete: 'structureDelete',
    structureSearch: 'structureSearch',
    structureUpdateDisplay: 'structureUpdateDisplay',
    departmentCreate: 'departmentCreate',
    departmentUpdate: 'departmentUpdate',
    departmentDelete: 'departmentDelete',
    departmentSearch: 'departmentSearch',
    menuCreate: 'menuCreate',
    menuUpdate: 'menuUpdate',
    menuDelete: 'menuDelete',
    menuSearch: 'menuSearch',
    menuUpdateDisplay: 'menuUpdateDisplay',
    digitalCreate: 'digitalCreate',
    digitalUpdate: 'digitalUpdate',
    digitalDelete: 'digitalDelete',
    digitalSearch: 'digitalSearch',
    digitalUpdateDisplay: 'digitalUpdateDisplay'
};
exports.permissions = {
    [exports.apiList.userSearch]: FullAccess,
    [exports.apiList.userSearchId]: FullAccess,
    [exports.apiList.userDelete]: NotUserAccess,
    [exports.apiList.userCreate]: FullAccess,
    [exports.apiList.userUpdate]: FullAccess,
    [exports.apiList.userUpdateSelf]: FullAccess,
    [exports.apiList.adminSearch]: FullAccess,
    [exports.apiList.adminSearchId]: FullAccess,
    [exports.apiList.adminInfo]: FullAccess,
    [exports.apiList.adminDelete]: NotUserAccess,
    [exports.apiList.adminCreate]: NotUserAccess,
    [exports.apiList.adminUpdate]: FullAccess,
    [exports.apiList.categoryCreate]: FullAccess,
    [exports.apiList.categoryUpdate]: FullAccess,
    [exports.apiList.categoryDelete]: FullAccess,
    [exports.apiList.categorySearchId]: FullAccess,
    [exports.apiList.categorySearch]: FullAccess,
    [exports.apiList.categoryDocumentCreate]: FullAccess,
    [exports.apiList.categoryDocumentUpdate]: FullAccess,
    [exports.apiList.categoryDocumentDelete]: FullAccess,
    [exports.apiList.categoryDocumentSearchId]: FullAccess,
    [exports.apiList.categoryDocumentSearch]: FullAccess,
    [exports.apiList.postCreate]: FullAccess,
    [exports.apiList.postUpdate]: FullAccess,
    [exports.apiList.postDelete]: FullAccess,
    [exports.apiList.postSearchId]: FullAccess,
    [exports.apiList.postSearch]: FullAccess,
    [exports.apiList.projectCreate]: FullAccess,
    [exports.apiList.projectUpdate]: FullAccess,
    [exports.apiList.projectDelete]: FullAccess,
    [exports.apiList.projectSearchId]: FullAccess,
    [exports.apiList.projectSearch]: FullAccess,
    [exports.apiList.documentCreate]: FullAccess,
    [exports.apiList.documentUpdate]: FullAccess,
    [exports.apiList.documentDelete]: FullAccess,
    [exports.apiList.documentSearchId]: FullAccess,
    [exports.apiList.documentSearch]: FullAccess,
    [exports.apiList.companyCreate]: FullAccess,
    [exports.apiList.companyUpdate]: FullAccess,
    [exports.apiList.companyUpdateDisplay]: FullAccess,
    [exports.apiList.companyDelete]: FullAccess,
    [exports.apiList.companySearchId]: FullAccess,
    [exports.apiList.companySearch]: FullAccess,
    [exports.apiList.slideCreate]: NotUserAccess,
    [exports.apiList.slideUpdate]: NotUserAccess,
    [exports.apiList.slideDelete]: NotUserAccess,
    [exports.apiList.slideSearch]: FullAccess,
    [exports.apiList.slideUpdateDisplay]: NotUserAccess,
    [exports.apiList.galleryCreate]: NotUserAccess,
    [exports.apiList.galleryUpdate]: NotUserAccess,
    [exports.apiList.galleryDelete]: NotUserAccess,
    [exports.apiList.gallerySearch]: FullAccess,
    [exports.apiList.publicationCreate]: NotUserAccess,
    [exports.apiList.publicationUpdate]: NotUserAccess,
    [exports.apiList.publicationDelete]: NotUserAccess,
    [exports.apiList.publicationSearch]: FullAccess,
    [exports.apiList.questionCreate]: NotUserAccess,
    [exports.apiList.questionUpdate]: NotUserAccess,
    [exports.apiList.questionDelete]: NotUserAccess,
    [exports.apiList.questionSearch]: FullAccess,
    [exports.apiList.structureCreate]: NotUserAccess,
    [exports.apiList.structureUpdate]: NotUserAccess,
    [exports.apiList.structureDelete]: NotUserAccess,
    [exports.apiList.structureSearch]: FullAccess,
    [exports.apiList.structureUpdateDisplay]: NotUserAccess,
    [exports.apiList.departmentCreate]: NotUserAccess,
    [exports.apiList.departmentUpdate]: NotUserAccess,
    [exports.apiList.departmentDelete]: NotUserAccess,
    [exports.apiList.departmentSearch]: FullAccess,
    [exports.apiList.menuCreate]: NotUserAccess,
    [exports.apiList.menuUpdate]: NotUserAccess,
    [exports.apiList.menuDelete]: NotUserAccess,
    [exports.apiList.menuSearch]: NotUserAccess,
    [exports.apiList.menuUpdateDisplay]: NotUserAccess,
    [exports.apiList.digitalCreate]: NotUserAccess,
    [exports.apiList.digitalUpdate]: NotUserAccess,
    [exports.apiList.digitalDelete]: NotUserAccess,
    [exports.apiList.digitalSearch]: FullAccess,
    [exports.apiList.digitalUpdateDisplay]: NotUserAccess,
    [exports.apiList.projectCreate]: FullAccess,
    [exports.apiList.projectUpdate]: FullAccess,
    [exports.apiList.projectDelete]: FullAccess,
    [exports.apiList.projectSearchId]: FullAccess,
    [exports.apiList.projectSearch]: FullAccess
};
/**
 * prevent user enter api without authorization
 * @param apiName name of api, define in `apiList`
 */
const routeGuard = (apiName) => {
    const apiPermission = exports.permissions[apiName];
    return (req, res, next) => {
        if (req.user && apiPermission.indexOf(req.user.role) >= 0) {
            next();
        }
        else {
            res.status(http_status_1.FORBIDDEN).json({
                errors: ['Unauthorized URL']
            });
        }
    };
};
exports.routeGuard = routeGuard;
//# sourceMappingURL=routeGuard.js.map